/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Rafael Diaz
 */
public class tallerBicicletas extends javax.swing.JFrame {

   
    public tallerBicicletas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_ListarClientes = new javax.swing.JButton();
        jButton_egresarCliente = new javax.swing.JButton();
        btn_ingresarCliente = new javax.swing.JButton();
        jButton_Estadobici = new javax.swing.JButton();
        jButton_manuales = new javax.swing.JButton();
        jButton_balance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_ListarClientes.setText("Listar total clientes ");
        jButton_ListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListarClientesActionPerformed(evt);
            }
        });

        jButton_egresarCliente.setText("Egresar cliente");
        jButton_egresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_egresarClienteActionPerformed(evt);
            }
        });

        btn_ingresarCliente.setText("Ingresar cliente");
        btn_ingresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarClienteActionPerformed(evt);
            }
        });

        jButton_Estadobici.setText("Estado bicicletas");
        jButton_Estadobici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EstadobiciActionPerformed(evt);
            }
        });

        jButton_manuales.setText("Manuales y ayuda");
        jButton_manuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_manualesActionPerformed(evt);
            }
        });

        jButton_balance.setText("Balance");
        jButton_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_balanceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("DUOC BIKES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_ingresarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jButton_egresarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Estadobici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ListarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_manuales, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_manuales, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Estadobici, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ingresarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_egresarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarClienteActionPerformed
ingresarCliente inCli = new ingresarCliente();
inCli.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresarClienteActionPerformed

    private void jButton_egresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_egresarClienteActionPerformed
     egresarCliente egCli = new egresarCliente();
egCli.setVisible(true);
this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton_egresarClienteActionPerformed

    private void jButton_EstadobiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EstadobiciActionPerformed
estadoBicicletas esBici = new estadoBicicletas();
esBici.setVisible(true);
this.setVisible(false);  


// TODO add your handling code here:
    }//GEN-LAST:event_jButton_EstadobiciActionPerformed

    private void jButton_ListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListarClientesActionPerformed
listarClientes listCli = new listarClientes();
listCli.setVisible(true);
this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ListarClientesActionPerformed

    private void jButton_manualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_manualesActionPerformed
manualesAyuda ayuda = new manualesAyuda();
ayuda.setVisible(true);
this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton_manualesActionPerformed

    private void jButton_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_balanceActionPerformed
balance balan = new balance();
balan.setVisible(true);
this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton_balanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tallerBicicletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tallerBicicletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tallerBicicletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tallerBicicletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tallerBicicletas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresarCliente;
    private javax.swing.JButton jButton_Estadobici;
    private javax.swing.JButton jButton_ListarClientes;
    private javax.swing.JButton jButton_balance;
    private javax.swing.JButton jButton_egresarCliente;
    private javax.swing.JButton jButton_manuales;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
